### ISSUE TITLE
请求添加SevTech Ages的汉化

### ISSUE THREAD

**Issue by InsulationSMT** [CFPAOrg/Modpack-GuideBook-i18n#10]
请求添加SevTech Ages的成就手册汉化_(:з)∠)_

**Comment by TartaricAcid** [comment]
收到

**Comment by Suripe** [comment]
请问下这包还没有汉化吗？

**Comment by TartaricAcid** [comment]
已经添加
<https://github.com/CFPAOrg/Modpack-GuideBook-i18n/tree/master/SevTech%20Ages/3.0.6>
