### ISSUE TITLE
sevtech部分词条无法正常读取汉化

### ISSUE THREAD

**Issue by beiai** [CFPAOrg/Modpack-GuideBook-i18n#104]
汉化文件中的~和|符号被转换成了url特殊转义字符%7e和%7c
导致汉化的词条无法被正常读取，批量替换后显示正常（共18个词条）

**Comment by beiai** [comment]
今天看了下好像说的不够详细，没说明是哪个文件
文件是这个resources\sevtechages\lang\zh_cn.lang

**Comment by 10935336** [comment]
@yaohuomhuom
