### ISSUE TITLE
格雷空岛（Greg Block）中的翻译把液体单位“毫升”翻译成了“升”

### ISSUE THREAD

**Issue by Lievent5703** [CFPAOrg/Modpack-GuideBook-i18n#112]
格雷空岛（Greg Block）中的翻译把液体单位“毫升”翻译成了“升”

不管是管道流量还是桶装液体单位都显示为“升”

已使用Greg Block整合包汉化2.2.1  和  i18n汉化模组

**Comment by Kiwi233** [comment]
GT里头从来没有毫升单位，要么是桶B，要么是毫桶mB=升L
