### ISSUE TITLE
将GregBlock1.2.0的任务转换成了1.3.1的

### ISSUE THREAD

**Issue by anyijun** [CFPAOrg/Modpack-GuideBook-i18n#16]
[DefaultQuests.zip](https://github.com/CFPAOrg/Modpack-GuideBook-i18n/files/2545137/DefaultQuests.zip)
希望有帮助吧 233

**Comment by TartaricAcid** [comment]
抱歉现在才看到这个问题，这边新版本已经通过脚本处理并发布好了，虽然没能用上，但是还是非常感谢你的翻译。现在 1.3.1 版本可以去 https://modpack.cfpa.team/ 下载了，如果发现有翻译问题，也还请多多批评。
