### ISSUE TITLE
Stone Block 2

### ISSUE THREAD

**Issue by mythpan1** [CFPAOrg/Modpack-GuideBook-i18n#76]
1.6开始根目录下就没有questpack文件夹了，改到config\ftbquest下了

**Comment by FormatToday** [comment]
> 1.6开始根目录下就没有questpack文件夹了，改到config\ftbquest下了

我正好今天准备玩一下Stone Block 2的1.7版，用汉化包确实没起作用。config\ftbques下本来有一些文件，我全部删除后把汉化包里那个normal.nbt复制进去，进游戏后发现任务书全空了。
词条变化应该不大，应该只是目录结构问题，希望各位大佬解决一下。

**Comment by 10935336** [comment]
摸了，一个任务一个NBT文件 这个我更不动了

**Comment by mythpan1** [comment]
嗯，我在一个一个填进去，确实非人类！

**Comment by myylmf** [comment]
1.7.0的翻译，下载压缩包
https://github.com/myylmf/Modpack-GuideBook-i18n/blob/master/project/Stone%20Block%202/1.7.0/questpacks/ftbquests.rar

**Comment by mythpan1** [comment]
> 摸了，一个任务一个NBT文件 这个我更不动了

别啊，已经有解决方案了，直接把normal.nbt放config/ftbquest下，ftb quest直接会自己转换的

**Comment by 10935336** [comment]
更完了

**Comment by 10935336** [comment]
感谢各路大神提供的解决方案，这些issue都可以关了
