### ISSUE TITLE
Stoneblock2已更新1.9.0 

### ISSUE THREAD

**Issue by FormatToday** [CFPAOrg/Modpack-GuideBook-i18n#85]
[顺手给出网址。。。](https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2686786)

**Comment by 10935336** [comment]
可别交issue了，1.9.0没有更新任务。事实上所有版本文件都是一样的，除了后面更改了文件结构。几百个文件我懒得在上传一次，你要是有心你可以传一份上来。

**Comment by FormatToday** [comment]
> 可别交issue了，1.9.0没有更新任务。事实上所有版本文件都是一样的，除了后面更改了文件结构。几百个文件我懒得在上传一次，你要是有心你可以传一份上来。

请问怎么汉化这个包，用什么工具。后面我来维护吧
